language: "perl"
perl:
    - "5.22.0"
install: "echo"
before_script:
    - perl -S cpanm -n Template B::Flags Test::LeakTrace AppConfig IO::Scalar
script: "perl Makefile.PL && make && make testcore"
notifications:
  recipients:
    hipchat: asplaPtBOlltlYvLaTOiApwh78TdFtkRuKWlab1S@163339_perlcc
  email:
    on_success: change
    on_failure: always
# fast_finish: http://blog.travis-ci.com/2013-11-27-fast-finishing-builds/
matrix:
  fast_finish: true
# See https://blog.afoolishmanifesto.com/posts/use-travis-et-al/
before_install:
     - git clone git://github.com/haarg/perl-travis-helper
     - source perl-travis-helper/init
     - build-perl
     - perl -V
     - build-dist
     - cd $BUILD_DIR
