name: B::C testsuite

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-docker-container-action

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  cprove:
    env:
      PERL_USE_UNSAFE_INC: 0
      AUTHOR_TESTING: 1
      AUTOMATED_TESTING: 1
      RELEASE_TESTING: 1
      VERBOSE: 0
      BC_DEVELOPING: 0
      WARNINGS: 0

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      # Limit: 20 total concurrent jobs for 'Free' GitHub plan
      #   https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
      matrix:
        test_dir:
          - 'base/*.t'
          - 'bctestc/*.t'
          - 'comp/*.t'
          - 'extra/*.t'
          - 'io/*.t'
          - 'mro/*.t'
          - 'op/[0-9a-e]*.t'
          - 'op/[f-m]*.t'
          - 'op/[n-s]*.t'
          - 'op/[t-z]*.t'
          - 're/[a-f]*.t'
          - 're/[g-q]*.t'
          - 're/r*.t'
          - 're/[s-z]*.t'
          - 'uni/*.t'

    container:
      image: cpanelos/perl-compiler:perl-v5.30.0

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: which perl
        run: ls -l $(which perl)
      - name: ls
        run: ls -l
      - name: make
        run: perl Makefile.PL installdirs=vendor
      - name: make install
        run: make -j4 install
      - name: setup PATH
        run: echo "::add-path::/usr/local/cpanel/3rdparty/perl/530/bin/"
      - name: which perlcc
        run: which perlcc
      - name: 'running test ${{ matrix.test_dir }}'
        run: ./cprove -j4 ${{ matrix.test_dir }}
